# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

install:
  - nvm install
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."

script:
  - npm run build:js
  - npm run build:css
  - source "$DEV_LIB_PATH/travis.script.sh"
  - |
    if [[ ! -z "$PHPUNIT_EXTRA_GROUP" ]]; then
      echo "Running phpunit group $PHPUNIT_EXTRA_GROUP"
      phpunit --group $PHPUNIT_EXTRA_GROUP
    fi

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  # These need to be exact matches, including whitespace!
  allow_failures:
    # PHP unit tests (7.3, WordPress trunk)
    - env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1
    # PHP and JavaScript unit tests (7.3, WordPress trunk, with code coverage)
    - env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1 RUN_PHPUNIT_COVERAGE=1
    # PHP unit tests (7.4, WordPress trunk)
    - env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1
      php: 7.4snapshot
  include:
    - stage: lint
      name: Lint (PHP, JavaScript, and configuration files)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpsyntax
      before_script:
        - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."
        - composer require --dev localheinz/composer-normalize --ignore-platform-reqs
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"
        - composer validate --no-check-all
        - composer normalize --dry-run
        - npm run lint
        - npm run build:js
      after_success:
        - npx sizereport --config

    - stage: test
      name: JavaScript unit tests
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint,xmllint,phpsyntax,phpunit
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"
        - npm run test:js -- --ci --cacheDirectory="$HOME/.jest-cache"

    - name: E2E tests
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint,xmllint,phpsyntax,phpunit PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=
      install:
        - nvm install
        - composer install
        - npm install
      script:
        - npm run build:js
        - npm run build:css
        - npm run env:start
        - npm run test:e2e:ci
        - npm run env:stop

    - name: PHP unit tests w/ external-http (7.3, WordPress latest)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                                INSTALL_PWA_PLUGIN=1 PHPUNIT_EXTRA_GROUP=external-http

    - name: PHP unit tests (7.2, WordPress latest)
      php: "7.2"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax                      INSTALL_PWA_PLUGIN=1

    - name: PHP unit tests (7.1, WordPress latest)
      php: "7.1"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax                      INSTALL_PWA_PLUGIN=1

    - name: PHP unit tests (7.0, WordPress latest)
      php: "7.0"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax                      INSTALL_PWA_PLUGIN=1

    - name: PHP unit tests (5.6, WordPress latest)
      php: "5.6"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,phpsyntax                      INSTALL_PWA_PLUGIN=1

    - name: PHP unit tests (5.4, WordPress 5.1)
      php: "5.4"
      env: WP_VERSION=5.1    DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (5.5, WordPress 5.0)
      php: "5.5"
      env: WP_VERSION=5.0    DEV_LIB_ONLY=phpunit,phpsyntax

    - name: PHP unit tests w/ external-http (5.6, WordPress 4.9)
      php: "5.6"
      env: WP_VERSION=4.9    DEV_LIB_ONLY=phpunit,phpsyntax                     PHPUNIT_EXTRA_GROUP=external-http

    - name: PHP unit tests (7.3, WordPress trunk)
      php: "7.3"
      env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1

    - name: PHP unit tests (7.4, WordPress trunk)
      php: "7.4snapshot"
      env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1

    - name: PHP and JavaScript unit tests (7.3, WordPress trunk, with code coverage)
      if: branch = develop AND type = push
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1 RUN_PHPUNIT_COVERAGE=1
      before_script:
        - echo "Running unit tests with code coverage..."
      script:
        - npm run build:js
        - npm run build:css
        - source "$DEV_LIB_PATH/travis.script.sh"
        - bash <(curl -s https://codecov.io/bash) -cF php -f /tmp/wordpress/src/wp-content/plugins/amp/build/logs/clover.xml
        - npm run test:js -- --collectCoverage
        - bash <(curl -s https://codecov.io/bash) -cF javascript -f build/logs/lcov.info
